import { Metadata } from "next";
import { siteConfig } from "@/config/site";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { StickyMobileActionBar } from "@/components/layout/StickyMobileActionBar";
import { FileText } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms & Conditions | Soul Power Energies",
  description: "Terms & Conditions of service for Soul Power Energies solar and EV website.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-[#F8F9FC] text-[#0F172A] font-sans antialiased">
      <Header />
      <main id="main-content" className="flex-1 sthira-hero-bg py-12 sm:py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
          <div className="border-b border-slate-200/80 pb-6 space-y-3">
            <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full sthira-pill bg-white text-[#D97706] text-xs font-bold border border-[#D97706]/30 shadow-sm uppercase tracking-wider">
              <FileText className="w-3.5 h-3.5" />
              <span>Terms of Service</span>
            </span>
            <h1 className="text-3xl sm:text-5xl font-black text-slate-900 tracking-tight">
              Terms &amp; Conditions<span className="text-[#D97706]">.</span>
            </h1>
            <p className="text-xs text-[#D97706] font-extrabold uppercase tracking-wider">Last updated: August 2026</p>
          </div>

          <div className="p-8 sm:p-12 rounded-[32px] sthira-card bg-white border border-slate-200/80 space-y-6 text-sm text-slate-700 leading-relaxed shadow-xl font-medium">
            <p className="text-base text-slate-800 leading-relaxed font-semibold">
              Welcome to the website of <strong className="text-slate-900 font-extrabold">Soul Power Energies</strong>. By accessing or using this website, you agree to comply with and be bound by the following Terms and Conditions.
            </p>

            <div className="space-y-3 pt-2 border-t border-slate-100">
              <h2 className="text-lg font-extrabold text-slate-900 flex items-center gap-2">
                <span className="text-[#D97706]">1.</span> Preliminary Estimator &amp; Information Accuracy
              </h2>
              <p>
                All energy generation figures, financial savings ranges, and system capacity recommendations generated by our online Solar Savings Estimator are strictly preliminary indicative estimates. They do not constitute guaranteed generation levels or fixed pricing. Final system sizing, output, and costs depend on an on-ground physical technical site assessment.
              </p>
            </div>

            <div className="space-y-3 pt-4 border-t border-slate-100">
              <h2 className="text-lg font-extrabold text-slate-900 flex items-center gap-2">
                <span className="text-[#D97706]">2.</span> Partnership &amp; Certification Attribution
              </h2>
              <p>
                {siteConfig.partner.wording} Soul Power Energies independently coordinates local site assessments and installation services in Kozhikode and Wayanad.
              </p>
            </div>

            <div className="space-y-3 pt-4 border-t border-slate-100">
              <h2 className="text-lg font-extrabold text-slate-900 flex items-center gap-2">
                <span className="text-[#D97706]">3.</span> Service Availability
              </h2>
              <p>
                Battery Energy Storage Systems (BESS) are presented as &ldquo;Coming Soon&rdquo; and are currently available for early interest registration only.
              </p>
            </div>

            <div className="space-y-3 pt-4 border-t border-slate-100">
              <h2 className="text-lg font-extrabold text-slate-900 flex items-center gap-2">
                <span className="text-[#D97706]">4.</span> Intellectual Property
              </h2>
              <p>
                All website design elements, custom layouts, text content, and graphics are owned by or licensed to Soul Power Energies. Brand logos and trademarks belong to their respective manufacturers.
              </p>
            </div>

            <div className="space-y-3 pt-4 border-t border-slate-100">
              <h2 className="text-lg font-extrabold text-slate-900 flex items-center gap-2">
                <span className="text-[#D97706]">5.</span> Governing Law
              </h2>
              <p>
                These Terms and Conditions shall be governed by and construed in accordance with the laws of India, under the jurisdiction of the courts of Kozhikode, Kerala.
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
      <StickyMobileActionBar />
    </div>
  );
}
