import { Metadata } from "next";
import { siteConfig } from "@/config/site";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { StickyMobileActionBar } from "@/components/layout/StickyMobileActionBar";

export const metadata: Metadata = {
  title: "Terms & Conditions | Soul Power Energies",
  description: "Terms & Conditions of service for Soul Power Energies solar and EV website.",
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <main id="main-content" className="flex-1 bg-white py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
          <div className="border-b border-slate-200 pb-6 space-y-2">
            <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 font-heading">
              Terms & Conditions
            </h1>
            <p className="text-xs text-slate-500">Last updated: August 2026</p>
          </div>

          <div className="prose prose-slate max-w-none space-y-6 text-sm text-slate-700 leading-relaxed">
            <p>
              Welcome to the website of <strong>Soul Power Energies</strong>. By accessing or using this website, you agree to comply with and be bound by the following Terms and Conditions.
            </p>

            <h2 className="text-lg font-bold text-slate-900 font-heading pt-2">1. Preliminary Estimator & Information Accuracy</h2>
            <p>
              All energy generation figures, financial savings ranges, and system capacity recommendations generated by our online Solar Savings Estimator are strictly preliminary indicative estimates. They do not constitute guaranteed generation levels or fixed pricing. Final system sizing, output, and costs depend on an on-ground physical technical site assessment.
            </p>

            <h2 className="text-lg font-bold text-slate-900 font-heading pt-2">2. Partnership & Certification Attribution</h2>
            <p>
              {siteConfig.partner.wording} Soul Power Energies independently coordinates local site assessments and installation services in Kozhikode and Wayanad.
            </p>

            <h2 className="text-lg font-bold text-slate-900 font-heading pt-2">3. Service Availability</h2>
            <p>
              Battery Energy Storage Systems (BESS) are presented as &ldquo;Coming Soon&rdquo; and are currently available for early interest registration only.
            </p>

            <h2 className="text-lg font-bold text-slate-900 font-heading pt-2">4. Intellectual Property</h2>
            <p>
              All website design elements, custom layouts, text content, and graphics are owned by or licensed to Soul Power Energies. Brand logos and trademarks belong to their respective manufacturers.
            </p>

            <h2 className="text-lg font-bold text-slate-900 font-heading pt-2">5. Governing Law</h2>
            <p>
              These Terms and Conditions shall be governed by and construed in accordance with the laws of India, under the jurisdiction of the courts of Kozhikode, Kerala.
            </p>
          </div>
        </div>
      </main>
      <Footer />
      <StickyMobileActionBar />
    </>
  );
}
